"""
FastAPI application entrypoint.

Run with:
    uvicorn app.main:app --reload --port 8000

Interactive API docs are then available at http://localhost:8000/docs
(auto-generated by FastAPI from the Pydantic schemas in app/models/schemas.py).
"""
from fastapi import FastAPI, Request
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse

from app.api.routes import router
from app.core.config import get_settings
from app.core.logging_config import configure_logging, get_logger

configure_logging()
log = get_logger("main")
settings = get_settings()

app = FastAPI(
    title="Financial AI Agent for Market Insights",
    description="Agentic financial research API: technical + fundamental analysis, "
                 "news sentiment, and SEC-filing RAG behind a single research endpoint.",
    version="0.1.0",
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=[settings.frontend_origin],
    allow_methods=["*"],
    allow_headers=["*"],
)

app.include_router(router)


@app.exception_handler(Exception)
async def unhandled_exception_handler(request: Request, exc: Exception) -> JSONResponse:
    """Catch-all so a failing external API (yfinance/SEC rate limits, etc.)
    returns a clean JSON error instead of a raw 500 stack trace — per the
    "return a useful error instead of fake data" reliability rule."""
    log.exception(f"Unhandled error on {request.url.path}: {exc}")
    return JSONResponse(status_code=500, content={"detail": "Internal error — see server logs for details."})


@app.get("/")
def root() -> dict:
    return {"status": "ok", "service": "financial-ai-agent-backend", "docs": "/docs"}


@app.get("/health")
def health() -> dict:
    return {"status": "healthy"}
